name: mlgeo-jensencc

channels:
  - conda-forge

dependencies:
  - python=3.10

  - blosc
  - curl
  - dask
  - datashader
  - earthengine-api
  - fsspec
  - gdal
  - geoviews  
  - geopandas
  - geemap
  - holoviews
  - hvplot
  - jupyter-panel-proxy
  - jupyterlab>=3
  - nbgitpuller
  - numpy
  - osgeo
  - pandas>=2.1.2
  # As of November 22, panel 1.3.2 and param 2.0 not working. So for now pin
  - panel<1
  - param<2
  - pip
  - progressbar2
  - qgis
  - rasterio
  - rioxarray
  - stackstac
  - tiledb
  
  - pip:
      - uni2ts
      - grimpfunc @ git+https://github.com/fastice/grimpfunc.git@master
      - grimpqgis @ git+https://github.com/fastice/grimpqgis.git@master
      - nisardev @ git+https://github.com/fastice/nisardev.git@main
