name: mlgeo-jensencc

channels:
  - conda-forge

dependencies:
  - python=3.10

  - blosc
  - curl
  - dask
  - datashader
  - earthengine-api
  - fsspec
  - gdal
  - geemap
  - geopandas
  - geoviews
  - holoviews
  - hvplot
  - jupyter-panel-proxy
  - jupyterlab>=3
  - matplotlib
  - nbgitpuller
  - numpy
  - pandas
  - panel<1
  - param<2
  - pip
  - progressbar2
  - qgis
  - rasterio
  - rioxarray
  - stackstac
  - tiledb
  - xarray
  
  - pip:
      - git+https://github.com/fastice/grimpfunc.git@master
      - git+https://github.com/fastice/grimpqgis.git@master
      - git+https://github.com/fastice/nisardev.git@main